spring:
  application:
    name: three-service

  config:
    import: optional:configserver:http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka