name: sample-microservices

services:
  one:
    build:
      context: one/one
    container_name: one-service
    ports:
      - "8084:8084"
    volumes:
      - maven_repo:/var/maven/.m2
    networks:
      - spring_network
    depends_on:
      - config

  two:
    build:
      context: two/two
    container_name: two-service
    ports:
      - "8085:8085"
    volumes:
      - maven_repo:/var/maven/.m2
    networks:
      - spring_network
    depends_on:
      - config

  three:
    build:
      context: three/three
    container_name: three-service
    ports:
      - "8086:8086"
    volumes:
      - maven_repo:/var/maven/.m2
    networks:
      - spring_network
    depends_on:
      - config

  config:
    build:
      context: config/config
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - maven_repo:/var/maven/.m2
    networks:
      - spring_network
    depends_on:
      - discovery

  discovery:
    build:
      context: discovery/discovery
    container_name: discovery
    ports:
      - "8761:8761"
    volumes:
      - maven_repo:/var/maven/.m2
    networks:
      - spring_network

volumes:
  maven_repo:

networks:
  spring_network:
    driver: bridge