spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
server:
  port: 8888
#  address: 0.0.0.0
endpoints:
  restart:
    enabled: true