spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka